name: DeployTestApplication

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.server }}
          user: ${{ secrets.username }}
          password: ${{ secrets.password }}
          remoteDir: "dev.legalex.by"
          options: "rm -r wwwroot/"

     
