name: DeployTestApplication

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Deploying application
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./build/
          server-dir: dev.legalex.by/
          options: "rmdir qwe/"
