name: DeployTestApplication

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Clean ReactJS precache-manifest and logs
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.server }}
          user: ${{ secrets.username }}
          password: ${{ secrets.password }}
          workingDir: "/dev.legalex.by"
          ignoreSSL: "1"
